config/routes.rb
Rails.application.routes.draw do

  root                'static_page#index'
  get    'index'   => 'static_page#index'
  get    'about'   => 'static_page#about'

  get    'signup'  => 'users#new'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'matching/find_compatibility'
  
  resources :users 
  resources :preferences
  

end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :user
  validates :question1, presence:true
  validates :question2, presence:true
  validates :question3, presence:true
  validates :question4, presence:true
  validates :question5, presence:true
  validates :question6, presence:true
  validates :user_id, presence:true
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)

    respond_to do |format|
      if @preference.save
        format.html { redirect_to current_user, notice: 'Preference was successfully created.' }
        format.json { render :show, status: :created, location: @preference }
      else
        format.html { render :new }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to current_user, notice: 'Preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url, notice: 'Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
#       @preference = Preference.find(params[:id])
      @preference = Preference.find_by_user_id(current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:question1, :question2, :question3, :question4, :question5, :question6, :user_id)
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
  def pref?
    !Preference.find_by_user_id(current_user).nil?
  end
  
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%@preference.user_id = current_user.id%>
<%= f.label "Pets Permitted:" %><br>
<%= f.select(:question1, [['Cats', 1], ['Dogs', 2],['Both', 3], ['Neither', 4]], { :class => 'form-control'}) %><br>
<%= f.label "The time of day I prefer to study is:" %><br>
<%= f.select(:question2, [['During the morning', 1], ['During the afternoon', 2],['During the evening', 3], ['Late at night', 4]]) %><br>
<%= f.label "I prefer the appearance of the room to be:" %><br>
<%= f.select(:question3, [['Usually orderly and clean', 1], ['Sometimes orderly and clean', 2],['Disorderly', 3]]) %><br>
<%= f.label "I would prefer approved visitors:" %><br>
<%= f.select(:question4, [['Be welcome anytime', 1], ['Leave when I sleep', 2],['Leave when I am in the room', 3], ['Just let me know when they are coming', 4]]) %><br>
<%= f.label "What are your sleeping habits?" %><br>
<%= f.select(:question5, [['Early Bird', 1], ['Night Owl', 2],['Sleep All Day', 3], ['Normal', 4]]) %><br>
<%= f.label "When I am upset, I need:" %><br>
<%= f.select(:question6, [['To talk about things', 1], ['Space and time to deal with it on my own', 2],['To be distracted', 3], ['To bake cookies', 4]]) %> <br>
<div class="hidden">
<%= f.label "User ID:" %><br><%= f.select(:user_id,[current_user.id])%><br><br>
</div>

<div class="actions">
   <%= f.submit %>
</div>

<% end %>
  
  

app/views/preferences/edit.html.erb
<div class="container">
<h1>Editing preference</h1>

<%= render 'form' %>


  <%= link_to 'Back', current_user %>

</div>

app/views/preferences/index.html.erb
<h1>All User's Preferences</h1>

<table>
  <thead>
    <tr>
      <th>User Names</th>
      <th>Pets Permitted</th>
      <th>Preferred time of day to study</th>
      <th>I prefer the appearance of the room to be</th>
      <th>I would prefer approved visitors</th>
      <th>My sleeping habits</th>
      <th>When I am upset, I need</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
    <% @content = []
    
  
    if preference.question2 == 1
      @content << "I prefer to study during the morning"
      elsif preference.question2 == 2
      @content << "I prefer to study during the afternoon"
      elsif preference.question2 == 3
      @content << "I prefer to study during the evening"
    else
      @content << "I prefer to study during late at night"
    end
  
    if preference.question3 == 1
      content << "My room is usually orderly and clean"
      elsif preference.question3 == 2
      content << "My room is sometimes orderly and clean"
    else
      content << "My room is disorderly"
    end
    
    if preference.question4 == 1
      content << "The visiotrs will be welcome any time"
      elsif preference.question4 == 2
      content << "The visitors should Leave when I sleep"
      elsif preference.question4 == 3
      content << "The visiotrs should leave when I am in the room"
    
    else
      content << "The visiotrs should just let me know when they are coming"
    end
    
    if preference.question5 == 1
      content << "My sleeping habit is early bird"
      elsif preference.question5 == 2
      content << "My sleeping habit is night owl"
      elsif preference.question5 == 3
      content << "My sleeping habit is sleep all day"
    else
      content << "My sleeping habit is mormal"
    end
    
   if preference.question6 == 1
     content << "When I upset, I need to talk about things"
      elsif preference.question6 == 2
     content << "When I upset, I need space and time to deal with it on my own"
      elsif preference.question6 == 3
     content << "When I upset, I need to to be distracted"
    else
     content << "When I upset, I need to bake cookies"
    end%>
      
    <%name = preference.user%> 
   
    
      <tr>
        <td><%= name.name %></td>
        <td><%= preference.question1 %></td>
        <td><%= @content[0] %></td>
        <td><%= preference.question3 %></td>
        <td><%= preference.question4 %></td>
        <td><%= preference.question5 %></td>
        <td><%= preference.question6 %></td>
        <td><%= link_to 'Show', preference %></td>
        <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
        <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<div class="container">
<h1 style="center">Preferred Living Conditions</h1>

<%= render 'form' %>

</end>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pets Permitted:</strong>
  <%= @preference.question1 %>
</p>

<p>
  <strong>The time of day I prefer to study is:</strong>
  <%= @preference.question2 %>
</p>

<p>
  <strong>I prefer the appearance of the room to be:</strong>
  <%= @preference.question3 %>
</p>

<p>
  <strong>I would prefer approved visitors:</strong>
  <%= @preference.question4 %>
</p>

<p>
  <strong>My sleeping habits:</strong>
  <%= @preference.question5 %>
</p>

<p>
  <strong>When I am upset, I need:</strong>
  <%= @preference.question6 %>
</p>

<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>